# Generated by Django 2.2.16 on 2021-03-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myshop', '0002_auto_20210306_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
